;; crt0.asm -- Custom SNES startup (replaces PVSnesLib's crt0_snes)
;;
;; Modeled on Doom SNES architecture:
;;   - Minimal startup: native mode, stack, DP, data bank
;;   - Clear WRAM for direct page and stack area
;;   - Disable display and interrupts
;;   - Call C main() entry point
;;   - Provide VBlank (NMI) and EmptyHandler for vectors
;;
;; Required labels for 816-tcc and hdr.asm:
;;   tcc__start    - RESET vector entry point
;;   VBlank        - NMI vector handler
;;   EmptyHandler  - unused vector handler
;;   tcc__r0..r10  - direct page register variables

.include "hdr.asm"

.accu 16
.index 16
.16bit

;; -------------------------------------------------------
;; Direct page register variables for 816-tcc
;; These MUST be at fixed DP offsets starting at $00
;; The compiler generates code like: lda.b tcc__r0
;; where .b means direct page addressing.
;; -------------------------------------------------------
.RAMSECTION ".tcc_regs" BANK 0 SLOT 1 ORG $00
tcc__r0     dsb 1     ; $00
tcc__r0h    dsb 1     ; $01
tcc__r1     dsb 1     ; $02
tcc__r1h    dsb 1     ; $03
tcc__r2     dsb 2     ; $04-$05
tcc__r3     dsb 2     ; $06-$07
tcc__r4     dsb 2     ; $08-$09
tcc__r5     dsb 2     ; $0A-$0B
tcc__r6     dsb 2     ; $0C-$0D
tcc__r7     dsb 2     ; $0E-$0F
tcc__r8     dsb 2     ; $10-$11
tcc__r9     dsb 2     ; $12-$13
tcc__r10    dsb 2     ; $14-$15
tcc__r11    dsb 2     ; $16-$17 (spare)
tcc__r12    dsb 2     ; $18-$19 (spare)
tcc__r13    dsb 2     ; $1A-$1B (spare)
tcc__r14    dsb 2     ; $1C-$1D (spare)
tcc__r15    dsb 2     ; $1E-$1F (spare)
.ENDS

;; -------------------------------------------------------
;; Global data section anchor (816-tcc APPENDTO target)
;; The compiled C code uses: .SECTION "xxx" APPENDTO "glob.data"
;; We must define the base section for it to append to.
;; This section holds const initialization data for C globals.
;; -------------------------------------------------------
.SECTION "glob.data" SUPERFREE KEEP
__glob_data_anchor:
  .db $00               ; anchor byte (required for APPENDTO linkage)
.ENDS

;; -------------------------------------------------------
;; Global RAM section anchor (816-tcc APPENDTO target)
;; The compiled C code uses: .RAMSECTION "xxx" APPENDTO "globram.data"
;; We must define the base RAM section for it to append to.
;; This section allocates WRAM for C global variables.
;; -------------------------------------------------------
.RAMSECTION "globram.data" BANK $7E SLOT 2 KEEP
__globram_data_anchor dsb 1    ; anchor byte (required for APPENDTO linkage)
.ENDS


;; -------------------------------------------------------
;; Startup code section
;; -------------------------------------------------------
.SECTION ".crt0_startup" SEMIFREE BANK 0 SLOT 0

tcc__start:
    ; Enter native mode (65816)
    clc
    xce

    ; Set 16-bit accumulator and index
    rep #$30

    ; Set stack pointer to $1FFF
    lda #$1FFF
    tcs

    ; Set direct page to $0000
    lda #$0000
    tcd

    ; Set data bank to $7E (WRAM)
    sep #$20
    lda #$7E
    pha
    plb
    rep #$20

    ; === Disable display (forced blank) ===
    sep #$20
    lda #$80
    sta.l $2100          ; INIDISP = forced blank

    ; === Disable NMI, IRQ, auto-joypad ===
    lda #$00
    sta.l $4200          ; NMITIMEN = all off

    ; === Clear PPU registers ===
    ; Zero out $2101-$2133 to reset all PPU state
    ldx #$2101
    rep #$20
@ClearPPU:
    sep #$20
    lda #$00
    sta.l $0000,x        ; absolute long write to $00:21xx
    rep #$20
    inx
    cpx #$2134
    bne @ClearPPU

    ; === Clear ALL WRAM via DMA ($7E:0000 - $7F:FFFF = 128KB) ===
    ; This ensures all C globals start at zero (ZSNES doesn't zero WRAM)
    sep #$20
    lda #$7E
    sta.l $2183          ; WMADDH = bank $7E
    rep #$20
    lda #$0000
    sta.l $2181          ; WMADDL = $0000
    sep #$20
    lda #$08             ; DMA mode: fixed source, A→B
    sta.l $4300
    lda #$80             ; B-bus: WMDATA ($2180)
    sta.l $4301
    rep #$20
    lda #zero_byte       ; source = ROM zero byte
    sta.l $4302
    sep #$20
    lda #:zero_byte
    sta.l $4304
    rep #$20
    lda #$0000           ; length = 0 = 64KB (clears bank $7E)
    sta.l $4305
    sep #$20
    lda #$01
    sta.l $420B          ; trigger DMA

    ; Clear bank $7F too
    lda #$7F
    sta.l $2183
    rep #$20
    lda #$0000
    sta.l $2181
    sta.l $4305          ; length = 0 = 64KB
    sep #$20
    lda #$01
    sta.l $420B          ; trigger DMA

    ; === Copy initialized C globals from ROM to WRAM ===
    ; glob.data (ROM) contains init values for globram.data (WRAM)
    ; Uses SECTIONSTART/SECTIONEND labels generated by wla-65816 -x flag
    rep #$30
    ldx #0
@CopyGlobals:
    lda.l SECTIONSTART_glob.data,x
    sta.l SECTIONSTART_globram.data,x
    inx
    inx
    cpx #(SECTIONEND_glob.data - SECTIONSTART_glob.data)
    bcc @CopyGlobals

    ; === Set 16-bit mode for C code ===
    rep #$30

    ; === Acknowledge any pending NMI/IRQ ===
    sep #$20
    lda.l $4210          ; read RDNMI to acknowledge
    lda.l $4211          ; read TIMEUP to acknowledge

    ; === Restore 16-bit mode for C runtime ===
    rep #$30

    ; === Call C main() ===
    ; 816-tcc compiles main() as a far subroutine (rtl)
    jsr.l main

    ; === If main returns, infinite loop ===
@Halt:
    wai
    bra @Halt

;; -------------------------------------------------------
;; VBlank -- Minimal NMI handler
;; Just acknowledge the NMI and return.
;; Our IRQ system does NOT use NMI (Doom-style: V-count IRQ only).
;; -------------------------------------------------------
VBlank:
    rep #$30
    pha
    sep #$20
    lda.l $4210          ; read RDNMI to acknowledge NMI
    rep #$20
    pla
    rti

;; -------------------------------------------------------
;; EmptyHandler -- Stub for unused vectors (COP, BRK, ABORT)
;; -------------------------------------------------------
EmptyHandler:
    rti


.ENDS
