;==LoRom==

.MEMORYMAP
  SLOTSIZE $8000
  DEFAULTSLOT 0
  SLOT 0 $8000
  SLOT 1 $0 $2000
  SLOT 2 $2000 $E000
  SLOT 3 $0 $10000
.ENDME

.ROMBANKSIZE $8000
.ROMBANKS 8

.SNESHEADER
  ID "ODYS"
  NAME "ODYSSEY SNES         "
  ;    "123456789012345678901"

  SLOWROM
  LOROM

  CARTRIDGETYPE $15             ; ROM+RAM+SuperFX
  ROMSIZE $09                   ; 4Mbit
  SRAMSIZE $05                  ; 256Kbit (SuperFX RAM)
  COUNTRY $01
  LICENSEECODE $00
  VERSION $00
.ENDSNES

.SNESNATIVEVECTOR
  COP EmptyHandler
  BRK EmptyHandler
  ABORT EmptyHandler
  NMI VBlank
  IRQ IRQTrampoline
.ENDNATIVEVECTOR

.SNESEMUVECTOR
  COP EmptyHandler
  ABORT EmptyHandler
  NMI EmptyHandler
  RESET tcc__start
  IRQBRK EmptyHandler
.ENDEMUVECTOR
