/* BSP tree data for 10x10 test map */
/* Generated by generate_bsp.py */

#define BSP_NUM_ENTRIES 44

/* BSP data: nodes and segments interleaved */
/* Node: plane(1), dir(1), child0_lo(1), child0_hi(1), child1_lo(1), child1_hi(1) */
/* Seg:  plane(1), dir(1), min(1), max(1), texture(1), area(1) */
const u8 bsp_data[264] = {
    /* [0] node: plane=8, vert, children=[1,30] */
    8, 1, 1, 0, 30, 0,
    /* [1] node: plane=12, vert, children=[2,16] */
    12, 1, 2, 0, 16, 0,
    /* [2] node: plane=8, horiz, children=[3,12] */
    8, 0, 3, 0, 12, 0,
    /* [3] node: plane=12, horiz, children=[4,8] */
    12, 0, 4, 0, 8, 0,
    /* [4] seg: plane=18, dir=$83, span=2-18, tex=1 */
    18, 131, 2, 18, 1, 0,
    /* [5] seg: plane=12, dir=$81, span=8-12, tex=2 */
    12, 129, 8, 12, 2, 0,
    /* [6] seg: plane=12, dir=$82, span=8-12, tex=2 */
    12, 130, 8, 12, 2, 0,
    /* [7] seg: plane=18, dir=$C0, span=2-18, tex=1 */
    18, 192, 2, 18, 1, 0,
    /* [8] seg: plane=18, dir=$83, span=2-18, tex=1 */
    18, 131, 2, 18, 1, 0,
    /* [9] seg: plane=8, dir=$80, span=8-12, tex=2 */
    8, 128, 8, 12, 2, 0,
    /* [10] seg: plane=12, dir=$81, span=8-12, tex=2 */
    12, 129, 8, 12, 2, 0,
    /* [11] seg: plane=12, dir=$C2, span=8-12, tex=2 */
    12, 194, 8, 12, 2, 0,
    /* [12] seg: plane=2, dir=$82, span=2-18, tex=1 */
    2, 130, 2, 18, 1, 0,
    /* [13] seg: plane=18, dir=$83, span=2-18, tex=1 */
    18, 131, 2, 18, 1, 0,
    /* [14] seg: plane=8, dir=$80, span=8-12, tex=2 */
    8, 128, 8, 12, 2, 0,
    /* [15] seg: plane=12, dir=$C1, span=8-12, tex=2 */
    12, 193, 8, 12, 2, 0,
    /* [16] node: plane=8, horiz, children=[17,26] */
    8, 0, 17, 0, 26, 0,
    /* [17] node: plane=12, horiz, children=[18,22] */
    12, 0, 18, 0, 22, 0,
    /* [18] seg: plane=8, dir=$83, span=8-12, tex=2 */
    8, 131, 8, 12, 2, 0,
    /* [19] seg: plane=12, dir=$81, span=8-12, tex=2 */
    12, 129, 8, 12, 2, 0,
    /* [20] seg: plane=12, dir=$82, span=8-12, tex=2 */
    12, 130, 8, 12, 2, 0,
    /* [21] seg: plane=18, dir=$C0, span=2-18, tex=1 */
    18, 192, 2, 18, 1, 0,
    /* [22] seg: plane=8, dir=$80, span=8-12, tex=2 */
    8, 128, 8, 12, 2, 0,
    /* [23] seg: plane=8, dir=$83, span=8-12, tex=2 */
    8, 131, 8, 12, 2, 0,
    /* [24] seg: plane=12, dir=$81, span=8-12, tex=2 */
    12, 129, 8, 12, 2, 0,
    /* [25] seg: plane=12, dir=$C2, span=8-12, tex=2 */
    12, 194, 8, 12, 2, 0,
    /* [26] seg: plane=2, dir=$82, span=2-18, tex=1 */
    2, 130, 2, 18, 1, 0,
    /* [27] seg: plane=8, dir=$80, span=8-12, tex=2 */
    8, 128, 8, 12, 2, 0,
    /* [28] seg: plane=8, dir=$83, span=8-12, tex=2 */
    8, 131, 8, 12, 2, 0,
    /* [29] seg: plane=12, dir=$C1, span=8-12, tex=2 */
    12, 193, 8, 12, 2, 0,
    /* [30] node: plane=8, horiz, children=[31,40] */
    8, 0, 31, 0, 40, 0,
    /* [31] node: plane=12, horiz, children=[32,36] */
    12, 0, 32, 0, 36, 0,
    /* [32] seg: plane=2, dir=$81, span=2-18, tex=1 */
    2, 129, 2, 18, 1, 0,
    /* [33] seg: plane=8, dir=$83, span=8-12, tex=2 */
    8, 131, 8, 12, 2, 0,
    /* [34] seg: plane=12, dir=$82, span=8-12, tex=2 */
    12, 130, 8, 12, 2, 0,
    /* [35] seg: plane=18, dir=$C0, span=2-18, tex=1 */
    18, 192, 2, 18, 1, 0,
    /* [36] seg: plane=2, dir=$81, span=2-18, tex=1 */
    2, 129, 2, 18, 1, 0,
    /* [37] seg: plane=8, dir=$80, span=8-12, tex=2 */
    8, 128, 8, 12, 2, 0,
    /* [38] seg: plane=8, dir=$83, span=8-12, tex=2 */
    8, 131, 8, 12, 2, 0,
    /* [39] seg: plane=12, dir=$C2, span=8-12, tex=2 */
    12, 194, 8, 12, 2, 0,
    /* [40] seg: plane=2, dir=$82, span=2-18, tex=1 */
    2, 130, 2, 18, 1, 0,
    /* [41] seg: plane=2, dir=$81, span=2-18, tex=1 */
    2, 129, 2, 18, 1, 0,
    /* [42] seg: plane=8, dir=$80, span=8-12, tex=2 */
    8, 128, 8, 12, 2, 0,
    /* [43] seg: plane=8, dir=$C3, span=8-12, tex=2 */
    8, 195, 8, 12, 2, 0,
};
