/* ============================================
 * Shared 16-color BGR555 palette
 * Auto-generated by tools/convert_textures_c.py
 * ============================================ */

#ifndef PALETTES_H
#define PALETTES_H

/* Colors 0-15: texture palette (0=black, 1-15=texture colors) */
const u16 shared_palette[16] = {
    0x0000, 0x194E, 0x110C, 0x0087, 0x1084, 0x0CCB, 0x1CE7, 0x35AD, 0x25B2, 0x18C6, 0x294A, 0x0C63, 0x14A5, 0x2529, 0x0842, 0x4210
};
/* Colors 16-17: ceiling and floor (loaded separately, no conflict with texture) */
const u16 extra_palette[2] = {
    0x7C00,  /* 16: blue (ceiling) */
    0x02A0   /* 17: dark green (floor) */
};

#endif /* PALETTES_H */
