#!/usr/bin/env python3
"""Generate C header lookup tables for SNES raycasting engine.

Outputs: data/tables.h

Tables generated:
  sin_table   - 256 entries, signed 8.8 fixed-point sine
  cos_table   - 256 entries, signed 8.8 fixed-point cosine
"""

import math
import os

BASE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir)
OUTPUT_PATH = os.path.join(BASE_DIR, "data", "tables.h")

VALUES_PER_LINE = 16


def to_signed_16(value):
    """Convert a float to signed 16-bit integer value (clamped)."""
    v = int(round(value))
    if v > 32767:
        v = 32767
    if v < -32768:
        v = -32768
    return v


def format_table_c(type_name, name, values, per_line=VALUES_PER_LINE):
    """Format a table as a C const array, 'per_line' values per line."""
    lines = [f"const {type_name} {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        vals = ", ".join(f"{v:d}" for v in chunk)
        if i + per_line < len(values):
            vals += ","
        lines.append(f"    {vals}")
    lines.append("};")
    return "\n".join(lines)


def generate_sin_table():
    """sin_table[i] = round(sin(i * 2*pi/256) * 256), signed 8.8 fixed-point."""
    values = []
    for i in range(256):
        angle = i * 2.0 * math.pi / 256.0
        raw = math.sin(angle) * 256.0
        values.append(to_signed_16(raw))
    return values


def generate_cos_table():
    """cos_table[i] = round(cos(i * 2*pi/256) * 256), signed 8.8 fixed-point."""
    values = []
    for i in range(256):
        angle = i * 2.0 * math.pi / 256.0
        raw = math.cos(angle) * 256.0
        values.append(to_signed_16(raw))
    return values


def main():
    sin_vals = generate_sin_table()
    cos_vals = generate_cos_table()

    header = (
        "/* ============================================\n"
        " * Lookup tables for SNES raycasting engine\n"
        " * Auto-generated by tools/generate_tables_c.py\n"
        " * ============================================ */\n"
        "\n"
        "#ifndef TABLES_H\n"
        "#define TABLES_H\n"
    )

    sections = [
        format_table_c("s16", "sin_table", sin_vals),
        format_table_c("s16", "cos_table", cos_vals),
    ]

    footer = "\n#endif /* TABLES_H */\n"

    output = header + "\n" + "\n\n".join(sections) + "\n" + footer

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", newline="\n") as f:
        f.write(output)

    print(f"Generated: {os.path.normpath(OUTPUT_PATH)}")
    print(f"  sin_table:    {len(sin_vals)} entries (signed 8.8)")
    print(f"  cos_table:    {len(cos_vals)} entries (signed 8.8)")
    print(f"  Format: C const s16 arrays, {VALUES_PER_LINE} values per line")


if __name__ == "__main__":
    main()
