#!/usr/bin/env python3
"""Generate WLA-DX assembly lookup tables for SNES raycasting engine.

Outputs: data/tables.inc

Tables generated:
  sin_table   - 256 entries, signed 8.8 fixed-point sine
  cos_table   - 256 entries, signed 8.8 fixed-point cosine
  recip_table - 256 entries, unsigned 16-bit reciprocal (1/x in 8.8)
  height_table- 256 entries, unsigned 16-bit wall height for distance d
"""

import math
import os

BASE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir)
OUTPUT_PATH = os.path.join(BASE_DIR, "data", "tables.inc")

VALUES_PER_LINE = 16


def to_signed_16(value):
    """Convert a signed integer to 16-bit two's complement unsigned representation."""
    v = int(round(value))
    if v < 0:
        v = v + 0x10000
    return v & 0xFFFF


def format_table(label, values, per_line=VALUES_PER_LINE):
    """Format a table as WLA-DX .dw directives, 'per_line' values per line."""
    lines = [f"{label}:"]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        hex_vals = ", ".join(f"${v:04X}" for v in chunk)
        lines.append(f"  .dw {hex_vals}")
    return "\n".join(lines)


def generate_sin_table():
    """sin_table[i] = round(sin(i * 2*pi/256) * 256), signed 8.8 fixed-point."""
    values = []
    for i in range(256):
        angle = i * 2.0 * math.pi / 256.0
        raw = math.sin(angle) * 256.0
        values.append(to_signed_16(raw))
    return values


def generate_cos_table():
    """cos_table[i] = round(cos(i * 2*pi/256) * 256), signed 8.8 fixed-point."""
    values = []
    for i in range(256):
        angle = i * 2.0 * math.pi / 256.0
        raw = math.cos(angle) * 256.0
        values.append(to_signed_16(raw))
    return values


def generate_recip_table():
    """recip_table[i] = min(round(256*256 / i), 65535) for i=1..255.
    recip_table[0] = 0xFFFF (infinity sentinel)."""
    values = [0xFFFF]  # index 0
    for i in range(1, 256):
        v = min(int(round(256.0 * 256.0 / i)), 65535)
        values.append(v)
    return values


def generate_height_table():
    """height_table[d] = min(round(128 * 256 / d), 65535) for d=1..255.
    height_table[0] = 128 (max viewport height)."""
    values = [128]  # index 0
    for d in range(1, 256):
        v = min(int(round(128.0 * 256.0 / d)), 65535)
        values.append(v)
    return values


def main():
    sin_vals = generate_sin_table()
    cos_vals = generate_cos_table()
    recip_vals = generate_recip_table()
    height_vals = generate_height_table()

    sections = [
        format_table("sin_table", sin_vals),
        format_table("cos_table", cos_vals),
        format_table("recip_table", recip_vals),
        format_table("height_table", height_vals),
    ]

    header = (
        "; ============================================\n"
        "; Lookup tables for SNES raycasting engine\n"
        "; Auto-generated by tools/generate_tables.py\n"
        "; ============================================\n"
    )

    output = header + "\n" + "\n\n".join(sections) + "\n"

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", newline="\n") as f:
        f.write(output)

    print(f"Generated: {os.path.normpath(OUTPUT_PATH)}")
    print(f"  sin_table:    {len(sin_vals)} entries (signed 8.8)")
    print(f"  cos_table:    {len(cos_vals)} entries (signed 8.8)")
    print(f"  recip_table:  {len(recip_vals)} entries (unsigned 16-bit)")
    print(f"  height_table: {len(height_vals)} entries (unsigned 16-bit)")
    print(f"  Format: .dw hex, {VALUES_PER_LINE} values per line")


if __name__ == "__main__":
    main()
