#!/usr/bin/env python3
"""Generate playback_bg with static perspective floor.

Floor rows near horizon are compressed (far away), rows at bottom are 1:1 (close).
Ceiling remains solid blue.
"""

import os, math
from PIL import Image
from collections import Counter

SCREEN_W = 112
CEIL_H = 40
FLOOR_H = 40
TEX_SIZE = 32
CEIL_COLOR = 16

BASE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir)
FLOORS_PATH = os.path.join(BASE_DIR, "assets", "floors.png")
WALLS_PATH = os.path.join(BASE_DIR, "assets", "walls.png")

def rgb_distance_sq(c1, c2):
    return sum((a - b) ** 2 for a, b in zip(c1, c2))

def nearest_index(rgb, palette):
    best, best_d = 0, float('inf')
    for i, c in enumerate(palette):
        d = rgb_distance_sq(rgb, c)
        if d < best_d:
            best_d, best = d, i
    return best

def main():
    walls_img = Image.open(WALLS_PATH).convert("RGBA")
    floors_img = Image.open(FLOORS_PATH).convert("RGBA")

    outer = walls_img.crop((0, 0, 32, 32))
    inner = walls_img.crop((192, 64, 224, 96))
    floor = floors_img.crop((0, 224, 32, 256))

    freq = Counter()
    for img in [outer, inner, floor]:
        for r, g, b, a in img.getdata():
            if a > 0:
                freq[(r, g, b)] += 1
    freq.pop((0, 0, 0), None)
    selected = [c for c, _ in freq.most_common(15)]
    palette = [(0, 0, 0)] + selected
    while len(palette) < 16:
        palette.append((0, 0, 0))

    # Index floor texture (row-major for easy 2D access)
    floor_rgba = list(floor.convert("RGBA").getdata())
    floor_grid = []  # floor_grid[row][col]
    for row in range(TEX_SIZE):
        row_data = []
        for col in range(TEX_SIZE):
            r, g, b, a = floor_rgba[row * TEX_SIZE + col]
            if a == 0:
                row_data.append(0)
            else:
                row_data.append(nearest_index((r, g, b), palette))
        floor_grid.append(row_data)

    # Generate perspective floor
    # For each floor row r (0=horizon, 39=bottom of screen):
    #   rowDistance = PROJ_CONST / (r + 0.5)  -- distance to this floor stripe
    #   For each column c (0-111):
    #     texU = (c - SCREEN_W/2) * rowDistance * TEX_SCALE + TEX_SIZE/2
    #     texV = rowDistance * TEX_SCALE
    # This creates a checkerboard-like perspective floor

    PROJ_CONST = 40.0   # controls how "deep" the perspective looks
    TEX_SCALE = 0.15     # controls texture tile density

    lines = []
    lines.append("; playback_bg: 112 columns x 80 bytes (ceiling + perspective floor)")
    lines.append("; Generated by generate_playback_bg.py")
    lines.append("playback_bg:")

    for col in range(SCREEN_W):
        col_bytes = []
        # Ceiling: 40 bytes solid blue
        for r in range(CEIL_H):
            col_bytes.append(CEIL_COLOR)

        # Floor: 40 bytes with perspective texture mapping
        for r in range(FLOOR_H):
            row_dist = PROJ_CONST / (r + 0.5)

            # texU depends on column position relative to center
            u = (col - SCREEN_W / 2) * row_dist * TEX_SCALE
            # texV depends on distance (depth into screen)
            v = row_dist * TEX_SCALE * 8

            tex_u = int(u) % TEX_SIZE
            tex_v = int(v) % TEX_SIZE

            pixel = floor_grid[tex_v][tex_u]
            col_bytes.append(pixel)

        for i in range(0, len(col_bytes), 16):
            chunk = col_bytes[i:i + 16]
            lines.append("    .db " + ", ".join(str(b) for b in chunk))

    with open("data/playback_bg.asm", "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated playback_bg with perspective floor ({SCREEN_W * (CEIL_H + FLOOR_H)} bytes)")

if __name__ == "__main__":
    main()
